[package]
name = "mnistndarray"
version = "0.1.0"
authors = ["James Welchman <james.welchman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.1"

[build-dependencies]
cc = "1.0"